export const FOLDER_VEHICULOS_VTV = process.env.FOLDER_VEHICULOS_VTV;

export const FOLDER_TRANSPORTES_CONSTANCIA_AFIP = process.env.FOLDER_TRANSPORTES_CONSTANCIA_AFIP;

export const FOLDER_CHOFERES_DNI_FRENTE = process.env.FOLDER_CHOFERES_DNI_FRENTE;
export const FOLDER_CHOFERES_DNI_DORSO = process.env.FOLDER_CHOFERES_DNI_DORSO;
export const FOLDER_CHOFERES_LICENCIA_CONDUCIR_FRENTE = process.env.FOLDER_CHOFERES_LICENCIA_CONDUCIR_FRENTE;
export const FOLDER_CHOFERES_LICENCIA_CONDUCIR_DORSO = process.env.FOLDER_CHOFERES_LICENCIA_CONDUCIR_DORSO;
export const FOLDER_CHOFERES_SEGURO_VEHICULO = process.env.FOLDER_CHOFERES_SEGURO_VEHICULO;
export const FOLDER_CHOFERES_SEGURO_VIDA = process.env.FOLDER_CHOFERES_SEGURO_VIDA;