INSERT INTO chofer_vehiculo (id_vehiculo, id_chofer, fecha_creacion) VALUES
((SELECT id FROM vehiculo WHERE patente='AB781PT'), (SELECT id FROM chofer WHERE nombre='NATALIA SANCHEZ'), current_date),
((SELECT id FROM vehiculo WHERE patente='BID450'), (SELECT id FROM chofer WHERE nombre='NICOLAS NICHEA'), current_date),
((SELECT id FROM vehiculo WHERE patente='IPT848'), (SELECT id FROM chofer WHERE nombre='CESAR FELIPE PEREYRA'), current_date),
((SELECT id FROM vehiculo WHERE patente='AA696LX'), (SELECT id FROM chofer WHERE nombre='BRIAN CARDOZO'), current_date),
((SELECT id FROM vehiculo WHERE patente='AB537DB'), (SELECT id FROM chofer WHERE nombre='COLTRINARI EDGARDO'), current_date),
((SELECT id FROM vehiculo WHERE patente='GUM372'), (SELECT id FROM chofer WHERE nombre='MORA WILFREDO'), current_date),
((SELECT id FROM vehiculo WHERE patente='DWM641'), (SELECT id FROM chofer WHERE nombre='MAXIMILIANO MARTORELLI'), current_date),
((SELECT id FROM vehiculo WHERE patente='HNR052'), (SELECT id FROM chofer WHERE nombre='GABRIEL DAMICO'), current_date),
((SELECT id FROM vehiculo WHERE patente='LSZ394'), (SELECT id FROM chofer WHERE nombre='NICOLAS OVIEDO'), current_date),
((SELECT id FROM vehiculo WHERE patente='SZA620'), (SELECT id FROM chofer WHERE nombre='ADRIAN KUKIN'), current_date),
((SELECT id FROM vehiculo WHERE patente='DNY420'), (SELECT id FROM chofer WHERE nombre='DIEGO BARON'), current_date),
((SELECT id FROM vehiculo WHERE patente='RHL885'), (SELECT id FROM chofer WHERE nombre='GABRIEL DAMICO'), current_date),
((SELECT id FROM vehiculo WHERE patente='AB405TA'), (SELECT id FROM chofer WHERE nombre='VICTOR  MAURO ZADIZ'), current_date),
((SELECT id FROM vehiculo WHERE patente='AXR397'), (SELECT id FROM chofer WHERE nombre='CORREA SERGIO'), current_date),
((SELECT id FROM vehiculo WHERE patente='SCV537'), (SELECT id FROM chofer WHERE nombre='ESTEBAN ZELARAYAN'), current_date),
((SELECT id FROM vehiculo WHERE patente='UZS653'), (SELECT id FROM chofer WHERE nombre='FABIAN ALEJANDRO ZELARAYAN'), current_date),
((SELECT id FROM vehiculo WHERE patente='WYV890'), (SELECT id FROM chofer WHERE nombre='JORGE ZELARAYAN'), current_date),
((SELECT id FROM vehiculo WHERE patente='LFC673'), (SELECT id FROM chofer WHERE nombre='GASTON SUAREZ'), current_date),
((SELECT id FROM vehiculo WHERE patente='AC373UJ'), (SELECT id FROM chofer WHERE nombre='PABLO GERMAN DEL BARCO'), current_date),
((SELECT id FROM vehiculo WHERE patente='BOR897'), (SELECT id FROM chofer WHERE nombre='SEBASTIAN ORSOMARSO'), current_date),
((SELECT id FROM vehiculo WHERE patente='KKH097'), (SELECT id FROM chofer WHERE nombre='JOSE LUIS'), current_date),
((SELECT id FROM vehiculo WHERE patente='PJT645'), (SELECT id FROM chofer WHERE nombre='ADRIAN CABRERA'), current_date),
((SELECT id FROM vehiculo WHERE patente='XAN669'), (SELECT id FROM chofer WHERE nombre='HERNAN COROMINAS'), current_date),
((SELECT id FROM vehiculo WHERE patente='NQB320'), (SELECT id FROM chofer WHERE nombre='GUSTAVO GIUJUSA'), current_date),
((SELECT id FROM vehiculo WHERE patente='GIX244'), (SELECT id FROM chofer WHERE nombre='ANGELOZZI LEANDRO'), current_date),
((SELECT id FROM vehiculo WHERE patente='SBZ446'), (SELECT id FROM chofer WHERE nombre='ENRIQUE ERCEGOVICH'), current_date),
((SELECT id FROM vehiculo WHERE patente='SQF335'), (SELECT id FROM chofer WHERE nombre='ZARAGOSA ROBERTO CARLOS'), current_date),
((SELECT id FROM vehiculo WHERE patente='LPO185'), (SELECT id FROM chofer WHERE nombre='DAMIAN ZANGARI'), current_date),
((SELECT id FROM vehiculo WHERE patente='IKL384'), (SELECT id FROM chofer WHERE nombre='GASTON CABRERA'), current_date),
((SELECT id FROM vehiculo WHERE patente='MPN809'), (SELECT id FROM chofer WHERE nombre='HERNAN MONZON'), current_date),
((SELECT id FROM vehiculo WHERE patente='VUN655'), (SELECT id FROM chofer WHERE nombre='JUAN BARRACCHIA'), current_date),
((SELECT id FROM vehiculo WHERE patente='JTH772'), (SELECT id FROM chofer WHERE nombre='IBER CALDERON'), current_date),
((SELECT id FROM vehiculo WHERE patente='AB829MO'), (SELECT id FROM chofer WHERE nombre='EZEQUIEL ROBLEDO'), current_date),
((SELECT id FROM vehiculo WHERE patente='IQQ638'), (SELECT id FROM chofer WHERE nombre='MATIAS DIAZ'), current_date),
((SELECT id FROM vehiculo WHERE patente='MYG271'), (SELECT id FROM chofer WHERE nombre='LUCAS ALANIZ'), current_date),
((SELECT id FROM vehiculo WHERE patente='FUW614'), (SELECT id FROM chofer WHERE nombre='DAMIAN PLAZA'), current_date),
((SELECT id FROM vehiculo WHERE patente='AB984RW'), (SELECT id FROM chofer WHERE nombre='FABIANA DYNOWSKY'), current_date),
((SELECT id FROM vehiculo WHERE patente='AB302GG'), (SELECT id FROM chofer WHERE nombre='PORRO MARTIN'), current_date),
((SELECT id FROM vehiculo WHERE patente='ECQ324'), (SELECT id FROM chofer WHERE nombre='MATIAS SILVEIRA'), current_date),
((SELECT id FROM vehiculo WHERE patente='FSM969'), (SELECT id FROM chofer WHERE nombre='OSVALDO SILVEIRA'), current_date),
((SELECT id FROM vehiculo WHERE patente='FPM619'), (SELECT id FROM chofer WHERE nombre='ZARAGOSA ROBERTO CARLOS'), current_date),
((SELECT id FROM vehiculo WHERE patente='AD225PN'), (SELECT id FROM chofer WHERE nombre='MATIAS NIEVAS'), current_date),
((SELECT id FROM vehiculo WHERE patente='GVV851'), (SELECT id FROM chofer WHERE nombre='SUAREZ JULIO CESAR'), current_date),
((SELECT id FROM vehiculo WHERE patente='HLJ473'), (SELECT id FROM chofer WHERE nombre='NICOLAS LOTTA'), current_date),
((SELECT id FROM vehiculo WHERE patente='OVM961'), (SELECT id FROM chofer WHERE nombre='JOSE MARQUEZ'), current_date),
((SELECT id FROM vehiculo WHERE patente='AB378AA'), (SELECT id FROM chofer WHERE nombre='LEANDRO SANDALIE'), current_date),
((SELECT id FROM vehiculo WHERE patente='FWN577'), (SELECT id FROM chofer WHERE nombre='MARCELO DAMIAN FUNES'), current_date),
((SELECT id FROM vehiculo WHERE patente='SDZ100'), (SELECT id FROM chofer WHERE nombre='GOMEZ FEDERICO ANDRES'), current_date),
((SELECT id FROM vehiculo WHERE patente='DLW906'), (SELECT id FROM chofer WHERE nombre='ACOSTA BRAIAN ARIEL'), current_date),
((SELECT id FROM vehiculo WHERE patente='UPP420'), (SELECT id FROM chofer WHERE nombre='DANIEL ALBERTO ROBLEDO'), current_date),
((SELECT id FROM vehiculo WHERE patente='ESY606'), (SELECT id FROM chofer WHERE nombre='SERGIO FUNES'), current_date),
((SELECT id FROM vehiculo WHERE patente='WJM159'), (SELECT id FROM chofer WHERE nombre='DANIEL GUSTAVO GARCIA'), current_date),
((SELECT id FROM vehiculo WHERE patente='CVQ207'), (SELECT id FROM chofer WHERE nombre='SERGIO ARIEL AMARILLO'), current_date),
((SELECT id FROM vehiculo WHERE patente='NQK812'), (SELECT id FROM chofer WHERE nombre='JESUS ELISEO CONDE'), current_date),
((SELECT id FROM vehiculo WHERE patente='AB855CA'), (SELECT id FROM chofer WHERE nombre='JUAN MANUEL LIND'), current_date),
((SELECT id FROM vehiculo WHERE patente='AC566WM'), (SELECT id FROM chofer WHERE nombre='SILVIA VELASCO'), current_date),
((SELECT id FROM vehiculo WHERE patente='FAT184'), (SELECT id FROM chofer WHERE nombre='FERNANDO MARTINI'), current_date),
((SELECT id FROM vehiculo WHERE patente='WRJ700'), (SELECT id FROM chofer WHERE nombre='LEONARDO JAVIER ALVAREZ'), current_date),
((SELECT id FROM vehiculo WHERE patente='RBC065'), (SELECT id FROM chofer WHERE nombre='ARIEL LUCERO'), current_date),
((SELECT id FROM vehiculo WHERE patente='TER562'), (SELECT id FROM chofer WHERE nombre='ISMAEL ESCOBAR'), current_date),
((SELECT id FROM vehiculo WHERE patente='HPM402'), (SELECT id FROM chofer WHERE nombre='RICARDO PEREZ'), current_date),
((SELECT id FROM vehiculo WHERE patente='RCL845'), (SELECT id FROM chofer WHERE nombre='GIAMMARINO ALEJANDRO'), current_date),
((SELECT id FROM vehiculo WHERE patente='EIF749'), (SELECT id FROM chofer WHERE nombre='SERGIO VELA'), current_date),
((SELECT id FROM vehiculo WHERE patente='ADJ899'), (SELECT id FROM chofer WHERE nombre='CRISTIAN AGUIRRE'), current_date),
((SELECT id FROM vehiculo WHERE patente='BVP968'), (SELECT id FROM chofer WHERE nombre='SERGIO MAIDANA'), current_date),
((SELECT id FROM vehiculo WHERE patente='USX306'), (SELECT id FROM chofer WHERE nombre='PABLO DANIEL DI BIASE'), current_date),
((SELECT id FROM vehiculo WHERE patente='CTX884'), (SELECT id FROM chofer WHERE nombre='GONZALO NAHUEL VESGA'), current_date),
((SELECT id FROM vehiculo WHERE patente='AA485BL'), (SELECT id FROM chofer WHERE nombre='IBER CALDERON'), current_date),
((SELECT id FROM vehiculo WHERE patente='AZD884'), (SELECT id FROM chofer WHERE nombre='BRAGA RODOLFO MARTIN'), current_date),
((SELECT id FROM vehiculo WHERE patente='ROX407'), (SELECT id FROM chofer WHERE nombre='JULIO CHAVEZ'), current_date),
((SELECT id FROM vehiculo WHERE patente='BAH252'), (SELECT id FROM chofer WHERE nombre='SCOTTO LUCAS FABIAN'), current_date),
((SELECT id FROM vehiculo WHERE patente='VQF691'), (SELECT id FROM chofer WHERE nombre='FEDERICO ALBORNOZ'), current_date),
((SELECT id FROM vehiculo WHERE patente='AA272PQ'), (SELECT id FROM chofer WHERE nombre='ANDRADA ANGEL ALEJANDRO'), current_date),
((SELECT id FROM vehiculo WHERE patente='AB553HD'), (SELECT id FROM chofer WHERE nombre='JULIO LOBATO'), current_date),
((SELECT id FROM vehiculo WHERE patente='AB902LO'), (SELECT id FROM chofer WHERE nombre='DAMIAN MARTINEZ'), current_date),
((SELECT id FROM vehiculo WHERE patente='AB952TK'), (SELECT id FROM chofer WHERE nombre='MAXIMO FRANCISCO LEON'), current_date),
((SELECT id FROM vehiculo WHERE patente='AC943HI'), (SELECT id FROM chofer WHERE nombre='GUSTAVO RODRIGUEZ'), current_date),
((SELECT id FROM vehiculo WHERE patente='AD170ZW'), (SELECT id FROM chofer WHERE nombre='MARCELO DI MAGGIO'), current_date),
((SELECT id FROM vehiculo WHERE patente='AD569AY'), (SELECT id FROM chofer WHERE nombre='ELIAS ALBERTO NUNEZ'), current_date),
((SELECT id FROM vehiculo WHERE patente='AE093NG'), (SELECT id FROM chofer WHERE nombre='SERGIO DENERI LOPEZ'), current_date),
((SELECT id FROM vehiculo WHERE patente='AE295DE'), (SELECT id FROM chofer WHERE nombre='SAVARRO ALEJANDRO'), current_date),
((SELECT id FROM vehiculo WHERE patente='AE393WF'), (SELECT id FROM chofer WHERE nombre='DIEGO CANOVAS'), current_date),
((SELECT id FROM vehiculo WHERE patente='AUN467'), (SELECT id FROM chofer WHERE nombre='CRISTIAN AQUINO'), current_date),
((SELECT id FROM vehiculo WHERE patente='CFX166'), (SELECT id FROM chofer WHERE nombre='ADRIAN GARRIGA'), current_date),
((SELECT id FROM vehiculo WHERE patente='CPQ147'), (SELECT id FROM chofer WHERE nombre='DAMIAN FLORES'), current_date),
((SELECT id FROM vehiculo WHERE patente='CYK456'), (SELECT id FROM chofer WHERE nombre='RICARDO JAVIER TRIPODI'), current_date),
((SELECT id FROM vehiculo WHERE patente='DLL168'), (SELECT id FROM chofer WHERE nombre='JOSE TORREL VICUNA'), current_date),
((SELECT id FROM vehiculo WHERE patente='DOZ672'), (SELECT id FROM chofer WHERE nombre='NESTOR AYALA'), current_date),
((SELECT id FROM vehiculo WHERE patente='DZO240'), (SELECT id FROM chofer WHERE nombre='TOMAS SANFILIPO'), current_date),
((SELECT id FROM vehiculo WHERE patente='EGW175'), (SELECT id FROM chofer WHERE nombre='EDGARDO ZELARAYAN'), current_date),
((SELECT id FROM vehiculo WHERE patente='EQI667'), (SELECT id FROM chofer WHERE nombre='FEDERICO TREJO'), current_date),
((SELECT id FROM vehiculo WHERE patente='ESM167'), (SELECT id FROM chofer WHERE nombre='CARLOS ARGARANAZ'), current_date),
((SELECT id FROM vehiculo WHERE patente='ETC039'), (SELECT id FROM chofer WHERE nombre='LEONEL BORGES'), current_date),
((SELECT id FROM vehiculo WHERE patente='FOX682'), (SELECT id FROM chofer WHERE nombre='CARLOS BERNANRDINO'), current_date),
((SELECT id FROM vehiculo WHERE patente='GCF029'), (SELECT id FROM chofer WHERE nombre='JORGE MUR'), current_date),
((SELECT id FROM vehiculo WHERE patente='GIX018'), (SELECT id FROM chofer WHERE nombre='GERONIMO FIGUEROA'), current_date),
((SELECT id FROM vehiculo WHERE patente='HAE992'), (SELECT id FROM chofer WHERE nombre='LUCHA FABIAN'), current_date),
((SELECT id FROM vehiculo WHERE patente='HCU142'), (SELECT id FROM chofer WHERE nombre='TOMAS SANFILIPO'), current_date),
((SELECT id FROM vehiculo WHERE patente='HHT836'), (SELECT id FROM chofer WHERE nombre='DANIELA DROGHETTI'), current_date),
((SELECT id FROM vehiculo WHERE patente='HIT091'), (SELECT id FROM chofer WHERE nombre='GERARDO MARTÍN WOHN'), current_date),
((SELECT id FROM vehiculo WHERE patente='HTJ337'), (SELECT id FROM chofer WHERE nombre='GONZALO MASCOTENA'), current_date),
((SELECT id FROM vehiculo WHERE patente='IBZ840'), (SELECT id FROM chofer WHERE nombre='BRIAN AGUSTIN BERTOCHE'), current_date),
((SELECT id FROM vehiculo WHERE patente='III272'), (SELECT id FROM chofer WHERE nombre='ALEX SOSA'), current_date),
((SELECT id FROM vehiculo WHERE patente='IOF799'), (SELECT id FROM chofer WHERE nombre='CRISTIAN FERRER'), current_date),
((SELECT id FROM vehiculo WHERE patente='JCX925'), (SELECT id FROM chofer WHERE nombre='MAURO PALACIOS'), current_date),
((SELECT id FROM vehiculo WHERE patente='JSQ064'), (SELECT id FROM chofer WHERE nombre='ANGEL RAFAEL'), current_date),
((SELECT id FROM vehiculo WHERE patente='JTE494'), (SELECT id FROM chofer WHERE nombre='NARCISO LAUREANO GABRIEL'), current_date),
((SELECT id FROM vehiculo WHERE patente='JVM446'), (SELECT id FROM chofer WHERE nombre='NICOLAS SIGNORELLI'), current_date),
((SELECT id FROM vehiculo WHERE patente='JXY214'), (SELECT id FROM chofer WHERE nombre='GONZALO GERMAN FERNANDEZ'), current_date),
((SELECT id FROM vehiculo WHERE patente='KMI621'), (SELECT id FROM chofer WHERE nombre='DIEGO SIMONE'), current_date),
((SELECT id FROM vehiculo WHERE patente='KON542'), (SELECT id FROM chofer WHERE nombre='JONATAN PINTO'), current_date),
((SELECT id FROM vehiculo WHERE patente='LEF812'), (SELECT id FROM chofer WHERE nombre='FERREYRA FEDERICO FABIAN'), current_date),
((SELECT id FROM vehiculo WHERE patente='LES592'), (SELECT id FROM chofer WHERE nombre='SANTIAGO VIEDMA'), current_date),
((SELECT id FROM vehiculo WHERE patente='LFJ651'), (SELECT id FROM chofer WHERE nombre='GONZALO FARIS'), current_date),
((SELECT id FROM vehiculo WHERE patente='LNY314'), (SELECT id FROM chofer WHERE nombre='LUCAS DARÍO GIANI'), current_date),
((SELECT id FROM vehiculo WHERE patente='LQQ739'), (SELECT id FROM chofer WHERE nombre='WINTER LEONARDO'), current_date),
((SELECT id FROM vehiculo WHERE patente='LSZ951'), (SELECT id FROM chofer WHERE nombre='LUIS VERA'), current_date),
((SELECT id FROM vehiculo WHERE patente='LTF683'), (SELECT id FROM chofer WHERE nombre='PEDUTTI MIGUEL ANGEL'), current_date),
((SELECT id FROM vehiculo WHERE patente='LUP665'), (SELECT id FROM chofer WHERE nombre='RODRIGO PEREZ'), current_date),
((SELECT id FROM vehiculo WHERE patente='MAX060'), (SELECT id FROM chofer WHERE nombre='NAHUEL CARLOS GÓMEZ SEGOVIA'), current_date),
((SELECT id FROM vehiculo WHERE patente='MGY089'), (SELECT id FROM chofer WHERE nombre='ACOSTA CARLOS DAVID'), current_date),
((SELECT id FROM vehiculo WHERE patente='MKZ034'), (SELECT id FROM chofer WHERE nombre='JULIAN ANDRES HERRERA'), current_date),
((SELECT id FROM vehiculo WHERE patente='MZE096'), (SELECT id FROM chofer WHERE nombre='BRAYEN LAURA'), current_date),
((SELECT id FROM vehiculo WHERE patente='NBX302'), (SELECT id FROM chofer WHERE nombre='HORACIO GABRIEL BARRERA'), current_date),
((SELECT id FROM vehiculo WHERE patente='NGB615'), (SELECT id FROM chofer WHERE nombre='MUNOZ GONZALO'), current_date),
((SELECT id FROM vehiculo WHERE patente='NLR066'), (SELECT id FROM chofer WHERE nombre='BUONAVENTURA BRIAN NAHUEL'), current_date),
((SELECT id FROM vehiculo WHERE patente='NOA200'), (SELECT id FROM chofer WHERE nombre='DAMIAN GONZALES'), current_date),
((SELECT id FROM vehiculo WHERE patente='NQU811'), (SELECT id FROM chofer WHERE nombre='FRÍAS HÉCTOR JOSÉ'), current_date),
((SELECT id FROM vehiculo WHERE patente='NSM865'), (SELECT id FROM chofer WHERE nombre='RAMON ROMERO'), current_date),
((SELECT id FROM vehiculo WHERE patente='NTB356'), (SELECT id FROM chofer WHERE nombre='SERRANO WALTER'), current_date),
((SELECT id FROM vehiculo WHERE patente='OAL095'), (SELECT id FROM chofer WHERE nombre='JULIO ARRIONDO'), current_date),
((SELECT id FROM vehiculo WHERE patente='PEW242'), (SELECT id FROM chofer WHERE nombre='OSCAR VILLALVA'), current_date),
((SELECT id FROM vehiculo WHERE patente='PGS838'), (SELECT id FROM chofer WHERE nombre='MAXIMILIANO EDGARDO HILLAR'), current_date),
((SELECT id FROM vehiculo WHERE patente='PKT242'), (SELECT id FROM chofer WHERE nombre='ERIBERTO JUARES PAVIA'), current_date),
((SELECT id FROM vehiculo WHERE patente='RSD192'), (SELECT id FROM chofer WHERE nombre='FLORENTIN JORGE LUIS'), current_date),
((SELECT id FROM vehiculo WHERE patente='UOZ636'), (SELECT id FROM chofer WHERE nombre='GERMAN BORGES'), current_date),
((SELECT id FROM vehiculo WHERE patente='BJK778'), (SELECT id FROM chofer WHERE nombre='DEPATRI MARTIN'), current_date),
((SELECT id FROM vehiculo WHERE patente='SLQ756'), (SELECT id FROM chofer WHERE nombre='CARMONA EMILIANO'), current_date),
((SELECT id FROM vehiculo WHERE patente='ADM727'), (SELECT id FROM chofer WHERE nombre='CRISTIAN VALLEJOS'), current_date),
((SELECT id FROM vehiculo WHERE patente='LZB239'), (SELECT id FROM chofer WHERE nombre='PABLO LUCERO'), current_date),
((SELECT id FROM vehiculo WHERE patente='JYZ922'), (SELECT id FROM chofer WHERE nombre='RAMON GILS'), current_date),
((SELECT id FROM vehiculo WHERE patente='DKO954'), (SELECT id FROM chofer WHERE nombre='LEIVA MARTIN'), current_date),
((SELECT id FROM vehiculo WHERE patente='VZL626'), (SELECT id FROM chofer WHERE nombre='EMANUEL DOMINGUEZ'), current_date),
((SELECT id FROM vehiculo WHERE patente='IZG414'), (SELECT id FROM chofer WHERE nombre='MAXIMILIANO GARCIA'), current_date),
((SELECT id FROM vehiculo WHERE patente='DRS571'), (SELECT id FROM chofer WHERE nombre='FABIAN RODRIGUEZ'), current_date),
((SELECT id FROM vehiculo WHERE patente='VZE688'), (SELECT id FROM chofer WHERE nombre='NICOLAS BOLLOTA'), current_date),
((SELECT id FROM vehiculo WHERE patente='SRB096'), (SELECT id FROM chofer WHERE nombre='EZEQUIEL ROBLEDO'), current_date),
((SELECT id FROM vehiculo WHERE patente='GSP426'), (SELECT id FROM chofer WHERE nombre='RUBEN SALCEDO'), current_date),
((SELECT id FROM vehiculo WHERE patente='GPQ469'), (SELECT id FROM chofer WHERE nombre='MAXIMILIANO LOBOS'), current_date),
((SELECT id FROM vehiculo WHERE patente='CZS339'), (SELECT id FROM chofer WHERE nombre='JUAN AGUERO'), current_date),
((SELECT id FROM vehiculo WHERE patente='AB162YB'), (SELECT id FROM chofer WHERE nombre='JUAN FLORES'), current_date),
((SELECT id FROM vehiculo WHERE patente='AA413NS'), (SELECT id FROM chofer WHERE nombre='MAXIMILIANO RODRIGUEZ'), current_date),
((SELECT id FROM vehiculo WHERE patente='HJQ412'), (SELECT id FROM chofer WHERE nombre='JONATAN RODRIGUEZ'), current_date),
((SELECT id FROM vehiculo WHERE patente='SEQ586'), (SELECT id FROM chofer WHERE nombre='FERNANDO INTILANGELO'), current_date),
((SELECT id FROM vehiculo WHERE patente='ERIK978'), (SELECT id FROM chofer WHERE nombre='ALEJANDRO FIGUEROA'), current_date),
((SELECT id FROM vehiculo WHERE patente='AA585KC'), (SELECT id FROM chofer WHERE nombre='JUAN GALINDRE'), current_date),
((SELECT id FROM vehiculo WHERE patente='XBV991'), (SELECT id FROM chofer WHERE nombre='NICOLAS ZERDAN'), current_date),
((SELECT id FROM vehiculo WHERE patente='BJQ986'), (SELECT id FROM chofer WHERE nombre='JOEL CUELLA'), current_date),
((SELECT id FROM vehiculo WHERE patente='LQK969'), (SELECT id FROM chofer WHERE nombre='MARTIN ABAN'), current_date),
((SELECT id FROM vehiculo WHERE patente='AC908NQ'), (SELECT id FROM chofer WHERE nombre='ARIEL RUFAS'), current_date),
((SELECT id FROM vehiculo WHERE patente='BNE400'), (SELECT id FROM chofer WHERE nombre='FERNANDO INTILANGELO'), current_date),
((SELECT id FROM vehiculo WHERE patente='AC582PL'), (SELECT id FROM chofer WHERE nombre='ALEJANDRO DOMINGUEZ'), current_date),
((SELECT id FROM vehiculo WHERE patente='WTV677'), (SELECT id FROM chofer WHERE nombre='DIEGO ROZZA'), current_date),
((SELECT id FROM vehiculo WHERE patente='RNP511'), (SELECT id FROM chofer WHERE nombre='GONZALO MARINO'), current_date),
((SELECT id FROM vehiculo WHERE patente='GUO795'), (SELECT id FROM chofer WHERE nombre='DAMIAN NICHEA'), current_date),
((SELECT id FROM vehiculo WHERE patente='AKS769'), (SELECT id FROM chofer WHERE nombre='CRISTIAN MOLINA'), current_date),
((SELECT id FROM vehiculo WHERE patente='PJP515'), (SELECT id FROM chofer WHERE nombre='GONZALO SANDOVAL'), current_date),
((SELECT id FROM vehiculo WHERE patente='JWR513'), (SELECT id FROM chofer WHERE nombre='ANTONIO AZCONA'), current_date),
((SELECT id FROM vehiculo WHERE patente='GRZ364'), (SELECT id FROM chofer WHERE nombre='ELIO MOYA'), current_date),
((SELECT id FROM vehiculo WHERE patente='OLF972'), (SELECT id FROM chofer WHERE nombre='NICOLAS CORREA'), current_date),
((SELECT id FROM vehiculo WHERE patente='AA397JG'), (SELECT id FROM chofer WHERE nombre='JONATAN PARDAL'), current_date),
((SELECT id FROM vehiculo WHERE patente='TTU723'), (SELECT id FROM chofer WHERE nombre='MATIAS MIÃ±O'), current_date),
((SELECT id FROM vehiculo WHERE patente='ARS460'), (SELECT id FROM chofer WHERE nombre='VESGA RUBEN'), current_date),
((SELECT id FROM vehiculo WHERE patente='CSM483'), (SELECT id FROM chofer WHERE nombre='LEONARDO CARRIZO'), current_date),
((SELECT id FROM vehiculo WHERE patente='KTK245'), (SELECT id FROM chofer WHERE nombre='VICTOR FERNANDEZ'), current_date),
((SELECT id FROM vehiculo WHERE patente='JWV266'), (SELECT id FROM chofer WHERE nombre='LEONARDO CARRIZO'), current_date),
((SELECT id FROM vehiculo WHERE patente='BHZ151'), (SELECT id FROM chofer WHERE nombre='CANO FACUNDO'), current_date),
((SELECT id FROM vehiculo WHERE patente='HXB341'), (SELECT id FROM chofer WHERE nombre='DOMINGO TRIPPOLONI'), current_date),
((SELECT id FROM vehiculo WHERE patente='AF667QX'), (SELECT id FROM chofer WHERE nombre='MARCELO JUAN DAVID CASAS'), current_date),
((SELECT id FROM vehiculo WHERE patente='HAO814'), (SELECT id FROM chofer WHERE nombre='JULIAN ARMENDARIZ'), current_date),
((SELECT id FROM vehiculo WHERE patente='CAF842'), (SELECT id FROM chofer WHERE nombre='RODRIGO LAUTARO GRAMAJO'), current_date),
((SELECT id FROM vehiculo WHERE patente='NLQ538'), (SELECT id FROM chofer WHERE nombre='OMAR ARCE'), current_date),
((SELECT id FROM vehiculo WHERE patente='GAZ175'), (SELECT id FROM chofer WHERE nombre='NICOLAS NICHEA'), current_date),
((SELECT id FROM vehiculo WHERE patente='WPU115'), (SELECT id FROM chofer WHERE nombre='DIEGO GASTON ESPINDOLA'), current_date),
((SELECT id FROM vehiculo WHERE patente='FXQ162'), (SELECT id FROM chofer WHERE nombre='SAMIR EMILIANO GALVAN'), current_date),
((SELECT id FROM vehiculo WHERE patente='HNR105'), (SELECT id FROM chofer WHERE nombre='LEANDRO MACEDA'), current_date),
((SELECT id FROM vehiculo WHERE patente='THD307'), (SELECT id FROM chofer WHERE nombre='CLAUDIO RIVERA'), current_date),
((SELECT id FROM vehiculo WHERE patente='AB781PT'), (SELECT id FROM chofer WHERE nombre='NATALIA SANCHEZ'), current_date),
((SELECT id FROM vehiculo WHERE patente='BID450'), (SELECT id FROM chofer WHERE nombre='NICOLAS NICHEA'), current_date),
((SELECT id FROM vehiculo WHERE patente='DWM641'), (SELECT id FROM chofer WHERE nombre='MAXIMILIANO MARTORELLI'), current_date),
((SELECT id FROM vehiculo WHERE patente='HNR052'), (SELECT id FROM chofer WHERE nombre='GABRIEL DAMICO'), current_date),
((SELECT id FROM vehiculo WHERE patente='DNY420'), (SELECT id FROM chofer WHERE nombre='DIEGO BARON'), current_date),
((SELECT id FROM vehiculo WHERE patente='UZS653'), (SELECT id FROM chofer WHERE nombre='FABIAN ALEJANDRO ZELARAYAN'), current_date),
((SELECT id FROM vehiculo WHERE patente='WYV890'), (SELECT id FROM chofer WHERE nombre='JORGE ZELARAYAN'), current_date),
((SELECT id FROM vehiculo WHERE patente='LFC673'), (SELECT id FROM chofer WHERE nombre='GASTON SUAREZ'), current_date),
((SELECT id FROM vehiculo WHERE patente='AC373UJ'), (SELECT id FROM chofer WHERE nombre='PABLO GERMAN DEL BARCO'), current_date),
((SELECT id FROM vehiculo WHERE patente='CCG617'), (SELECT id FROM chofer WHERE nombre='MARCELO GALINDRE'), current_date),
((SELECT id FROM vehiculo WHERE patente='KKH097'), (SELECT id FROM chofer WHERE nombre='JOSE LUIS'), current_date),
((SELECT id FROM vehiculo WHERE patente='PJT645'), (SELECT id FROM chofer WHERE nombre='ADRIAN CABRERA'), current_date),
((SELECT id FROM vehiculo WHERE patente='XAN669'), (SELECT id FROM chofer WHERE nombre='HERNAN COROMINAS'), current_date),
((SELECT id FROM vehiculo WHERE patente='HIE544'), (SELECT id FROM chofer WHERE nombre='MATIAS CASTILLO'), current_date),
((SELECT id FROM vehiculo WHERE patente='GIX244'), (SELECT id FROM chofer WHERE nombre='ANGELOZZI LEANDRO'), current_date),
((SELECT id FROM vehiculo WHERE patente='SQF335'), (SELECT id FROM chofer WHERE nombre='ZARAGOSA ROBERTO CARLOS'), current_date),
((SELECT id FROM vehiculo WHERE patente='IQQ638'), (SELECT id FROM chofer WHERE nombre='MATIAS DIAZ'), current_date),
((SELECT id FROM vehiculo WHERE patente='FUW614'), (SELECT id FROM chofer WHERE nombre='DAMIAN PLAZA'), current_date),
((SELECT id FROM vehiculo WHERE patente='AB302GG'), (SELECT id FROM chofer WHERE nombre='PORRO MARTIN'), current_date),
((SELECT id FROM vehiculo WHERE patente='FPM619'), (SELECT id FROM chofer WHERE nombre='ZARAGOSA ROBERTO CARLOS'), current_date),
((SELECT id FROM vehiculo WHERE patente='WJM159'), (SELECT id FROM chofer WHERE nombre='DANIEL GUSTAVO GARCIA'), current_date),
((SELECT id FROM vehiculo WHERE patente='RBC065'), (SELECT id FROM chofer WHERE nombre='ARIEL LUCERO'), current_date),
((SELECT id FROM vehiculo WHERE patente='ADJ899'), (SELECT id FROM chofer WHERE nombre='CRISTIAN AGUIRRE'), current_date),
((SELECT id FROM vehiculo WHERE patente='BVP968'), (SELECT id FROM chofer WHERE nombre='SERGIO MAIDANA'), current_date),
((SELECT id FROM vehiculo WHERE patente='VQF691'), (SELECT id FROM chofer WHERE nombre='FEDERICO ALBORNOZ'), current_date),
((SELECT id FROM vehiculo WHERE patente='AC943HI'), (SELECT id FROM chofer WHERE nombre='GUSTAVO RODRIGUEZ'), current_date),
((SELECT id FROM vehiculo WHERE patente='AE093NG'), (SELECT id FROM chofer WHERE nombre='SERGIO DENERI LOPEZ'), current_date),
((SELECT id FROM vehiculo WHERE patente='CFX166'), (SELECT id FROM chofer WHERE nombre='ADRIAN GARRIGA'), current_date),
((SELECT id FROM vehiculo WHERE patente='EGW175'), (SELECT id FROM chofer WHERE nombre='EDGARDO ZELARAYAN'), current_date),
((SELECT id FROM vehiculo WHERE patente='ESM167'), (SELECT id FROM chofer WHERE nombre='CARLOS ARGARANAZ'), current_date),
((SELECT id FROM vehiculo WHERE patente='ETC039'), (SELECT id FROM chofer WHERE nombre='LEONEL BORGES'), current_date),
((SELECT id FROM vehiculo WHERE patente='IBZ840'), (SELECT id FROM chofer WHERE nombre='BRIAN AGUSTIN BERTOCHE'), current_date),
((SELECT id FROM vehiculo WHERE patente='JCX925'), (SELECT id FROM chofer WHERE nombre='MAURO PALACIOS'), current_date),
((SELECT id FROM vehiculo WHERE patente='LQQ739'), (SELECT id FROM chofer WHERE nombre='WINTER LEONARDO'), current_date),
((SELECT id FROM vehiculo WHERE patente='LSZ951'), (SELECT id FROM chofer WHERE nombre='LUIS VERA'), current_date),
((SELECT id FROM vehiculo WHERE patente='LTF683'), (SELECT id FROM chofer WHERE nombre='PEDUTTI MIGUEL ANGEL'), current_date),
((SELECT id FROM vehiculo WHERE patente='LUP665'), (SELECT id FROM chofer WHERE nombre='RODRIGO PEREZ'), current_date),
((SELECT id FROM vehiculo WHERE patente='MAX060'), (SELECT id FROM chofer WHERE nombre='NAHUEL CARLOS GÓMEZ SEGOVIA'), current_date),
((SELECT id FROM vehiculo WHERE patente='MGY089'), (SELECT id FROM chofer WHERE nombre='ACOSTA CARLOS DAVID'), current_date),
((SELECT id FROM vehiculo WHERE patente='MKZ034'), (SELECT id FROM chofer WHERE nombre='JULIAN ANDRES HERRERA'), current_date),
((SELECT id FROM vehiculo WHERE patente='MZE096'), (SELECT id FROM chofer WHERE nombre='BRAYEN LAURA'), current_date),
((SELECT id FROM vehiculo WHERE patente='NBX302'), (SELECT id FROM chofer WHERE nombre='HORACIO GABRIEL BARRERA'), current_date),
((SELECT id FROM vehiculo WHERE patente='NGB615'), (SELECT id FROM chofer WHERE nombre='MUNOZ GONZALO'), current_date),
((SELECT id FROM vehiculo WHERE patente='NLR066'), (SELECT id FROM chofer WHERE nombre='BUONAVENTURA BRIAN NAHUEL'), current_date),
((SELECT id FROM vehiculo WHERE patente='NOA200'), (SELECT id FROM chofer WHERE nombre='DAMIAN GONZALES'), current_date),
((SELECT id FROM vehiculo WHERE patente='NQU811'), (SELECT id FROM chofer WHERE nombre='FRÍAS HÉCTOR JOSÉ'), current_date),
((SELECT id FROM vehiculo WHERE patente='NSM865'), (SELECT id FROM chofer WHERE nombre='RAMON ROMERO'), current_date),
((SELECT id FROM vehiculo WHERE patente='NTB356'), (SELECT id FROM chofer WHERE nombre='SERRANO WALTER'), current_date),
((SELECT id FROM vehiculo WHERE patente='OAL095'), (SELECT id FROM chofer WHERE nombre='JULIO ARRIONDO'), current_date),
((SELECT id FROM vehiculo WHERE patente='PEW242'), (SELECT id FROM chofer WHERE nombre='OSCAR VILLALVA'), current_date),
((SELECT id FROM vehiculo WHERE patente='PGS838'), (SELECT id FROM chofer WHERE nombre='MAXIMILIANO EDGARDO HILLAR'), current_date),
((SELECT id FROM vehiculo WHERE patente='PKT242'), (SELECT id FROM chofer WHERE nombre='ERIBERTO JUARES PAVIA'), current_date),
((SELECT id FROM vehiculo WHERE patente='RSD192'), (SELECT id FROM chofer WHERE nombre='FLORENTIN JORGE LUIS'), current_date),
((SELECT id FROM vehiculo WHERE patente='UOZ636'), (SELECT id FROM chofer WHERE nombre='GERMAN BORGES'), current_date),
((SELECT id FROM vehiculo WHERE patente='ADM727'), (SELECT id FROM chofer WHERE nombre='CRISTIAN VALLEJOS'), current_date),
((SELECT id FROM vehiculo WHERE patente='LZB239'), (SELECT id FROM chofer WHERE nombre='PABLO LUCERO'), current_date),
((SELECT id FROM vehiculo WHERE patente='DRS571'), (SELECT id FROM chofer WHERE nombre='FABIAN RODRIGUEZ'), current_date),
((SELECT id FROM vehiculo WHERE patente='SRB096'), (SELECT id FROM chofer WHERE nombre='EZEQUIEL ROBLEDO'), current_date),
((SELECT id FROM vehiculo WHERE patente='CZS339'), (SELECT id FROM chofer WHERE nombre='JUAN AGUERO'), current_date),
((SELECT id FROM vehiculo WHERE patente='AA413NS'), (SELECT id FROM chofer WHERE nombre='MAXIMILIANO RODRIGUEZ'), current_date),
((SELECT id FROM vehiculo WHERE patente='AA585KC'), (SELECT id FROM chofer WHERE nombre='JUAN GALINDRE'), current_date),
((SELECT id FROM vehiculo WHERE patente='BJQ986'), (SELECT id FROM chofer WHERE nombre='JOEL CUELLA'), current_date),
((SELECT id FROM vehiculo WHERE patente='LQK969'), (SELECT id FROM chofer WHERE nombre='MARTIN ABAN'), current_date),
((SELECT id FROM vehiculo WHERE patente='AC908NQ'), (SELECT id FROM chofer WHERE nombre='ARIEL RUFAS'), current_date),
((SELECT id FROM vehiculo WHERE patente='RNP511'), (SELECT id FROM chofer WHERE nombre='GONZALO MARINO'), current_date),
((SELECT id FROM vehiculo WHERE patente='VVY939MB'), (SELECT id FROM chofer WHERE nombre='MARCELO OCAMPO'), current_date),
((SELECT id FROM vehiculo WHERE patente='GUO795'), (SELECT id FROM chofer WHERE nombre='DAMIAN NICHEA'), current_date),
((SELECT id FROM vehiculo WHERE patente='GRZ364'), (SELECT id FROM chofer WHERE nombre='ELIO MOYA'), current_date),
((SELECT id FROM vehiculo WHERE patente='AA397JG'), (SELECT id FROM chofer WHERE nombre='JONATAN PARDAL'), current_date),
((SELECT id FROM vehiculo WHERE patente='CSM483'), (SELECT id FROM chofer WHERE nombre='LEONARDO CARRIZO'), current_date),
((SELECT id FROM vehiculo WHERE patente='JWV266'), (SELECT id FROM chofer WHERE nombre='LEONARDO CARRIZO'), current_date),
((SELECT id FROM vehiculo WHERE patente='BHZ151'), (SELECT id FROM chofer WHERE nombre='CANO FACUNDO'), current_date),
((SELECT id FROM vehiculo WHERE patente='AF667QX'), (SELECT id FROM chofer WHERE nombre='MARCELO JUAN DAVID CASAS'), current_date),
((SELECT id FROM vehiculo WHERE patente='HAO814'), (SELECT id FROM chofer WHERE nombre='JULIAN ARMENDARIZ'), current_date),
((SELECT id FROM vehiculo WHERE patente='NLQ538'), (SELECT id FROM chofer WHERE nombre='OMAR ARCE'), current_date),
((SELECT id FROM vehiculo WHERE patente='GAZ175'), (SELECT id FROM chofer WHERE nombre='NICOLAS NICHEA'), current_date),
((SELECT id FROM vehiculo WHERE patente='WPU115'), (SELECT id FROM chofer WHERE nombre='DIEGO GASTON ESPINDOLA'), current_date),
((SELECT id FROM vehiculo WHERE patente='FXQ162'), (SELECT id FROM chofer WHERE nombre='SAMIR EMILIANO GALVAN'), current_date),
((SELECT id FROM vehiculo WHERE patente='HNR105'), (SELECT id FROM chofer WHERE nombre='LEANDRO MACEDA'), current_date),
((SELECT id FROM vehiculo WHERE patente='THD307'), (SELECT id FROM chofer WHERE nombre='CLAUDIO RIVERA'), current_date),
((SELECT id FROM vehiculo WHERE patente='CZF739'), (SELECT id FROM chofer WHERE nombre='JUAN CARLOS SARAVIA'), current_date),
((SELECT id FROM vehiculo WHERE patente='VVY939MV'), (SELECT id FROM chofer WHERE nombre='AQUINO RODRIGO'), current_date),
((SELECT id FROM vehiculo WHERE patente='CIC902'), (SELECT id FROM chofer WHERE nombre='MIRANDA MARCELO SERGIO'), current_date),
((SELECT id FROM vehiculo WHERE patente='WKO365'), (SELECT id FROM chofer WHERE nombre='JUAREZ DANIEL ADRIAN'), current_date),
((SELECT id FROM vehiculo WHERE patente='AF761HL'), (SELECT id FROM chofer WHERE nombre='ADRIAN MENDIETA'), current_date),
((SELECT id FROM vehiculo WHERE patente='KFU735'), (SELECT id FROM chofer WHERE nombre='NELSON MARTÍNEZ'), current_date),
((SELECT id FROM vehiculo WHERE patente='HJJ934'), (SELECT id FROM chofer WHERE nombre='RICARDO CABALLERO'), current_date),
((SELECT id FROM vehiculo WHERE patente='EJZ558'), (SELECT id FROM chofer WHERE nombre='DARIO BUONAVENTURA'), current_date),
((SELECT id FROM vehiculo WHERE patente='AGW792'), (SELECT id FROM chofer WHERE nombre='DANIEL DENIA'), current_date),
((SELECT id FROM vehiculo WHERE patente='WXA444'), (SELECT id FROM chofer WHERE nombre='NICOLAS BORDALLO'), current_date),
((SELECT id FROM vehiculo WHERE patente='FOS177'), (SELECT id FROM chofer WHERE nombre='SEBASTIAN EZEQUIEL BORDALLO'), current_date),
((SELECT id FROM vehiculo WHERE patente='SCK863'), (SELECT id FROM chofer WHERE nombre='LEONEL DAVID'), current_date),
((SELECT id FROM vehiculo WHERE patente='OUU805'), (SELECT id FROM chofer WHERE nombre='GABRIEL SUELDO'), current_date),
((SELECT id FROM vehiculo WHERE patente='BKJ228'), (SELECT id FROM chofer WHERE nombre='MATIAS AMORES'), current_date),
((SELECT id FROM vehiculo WHERE patente='AQY121'), (SELECT id FROM chofer WHERE nombre='CRISTIAN MIÑO'), current_date),
((SELECT id FROM vehiculo WHERE patente='GNF145'), (SELECT id FROM chofer WHERE nombre='NICOLAS MARTINO'), current_date),
((SELECT id FROM vehiculo WHERE patente='GBK344'), (SELECT id FROM chofer WHERE nombre='JOSE FAZZINI'), current_date),
((SELECT id FROM vehiculo WHERE patente='ETI842'), (SELECT id FROM chofer WHERE nombre='NICOLAS PEREZ'), current_date),
((SELECT id FROM vehiculo WHERE patente='EGH110'), (SELECT id FROM chofer WHERE nombre='FRANCO ACUÑA'), current_date),
((SELECT id FROM vehiculo WHERE patente='OOP799'), (SELECT id FROM chofer WHERE nombre='LEONARDO AMAYA'), current_date),
((SELECT id FROM vehiculo WHERE patente='DMF360'), (SELECT id FROM chofer WHERE nombre='MATIAS CASTILLO'), current_date),
((SELECT id FROM vehiculo WHERE patente='SVD931'), (SELECT id FROM chofer WHERE nombre='CRISTIAN MATEOS'), current_date),
((SELECT id FROM vehiculo WHERE patente='NYA381'), (SELECT id FROM chofer WHERE nombre='LUIS SANCHEZ'), current_date),
((SELECT id FROM vehiculo WHERE patente='AC768QI'), (SELECT id FROM chofer WHERE nombre='WALTER PEÑATE'), current_date),
((SELECT id FROM vehiculo WHERE patente='LXE408'), (SELECT id FROM chofer WHERE nombre='GUSTAVO CUBILLA'), current_date),
((SELECT id FROM vehiculo WHERE patente='OTG144'), (SELECT id FROM chofer WHERE nombre='AMILCAR OPPEDISANO'), current_date),
((SELECT id FROM vehiculo WHERE patente='TOR709'), (SELECT id FROM chofer WHERE nombre='EMANUEL BORDALLO'), current_date),
((SELECT id FROM vehiculo WHERE patente='KBS112'), (SELECT id FROM chofer WHERE nombre='LUIS REINOSO'), current_date),
((SELECT id FROM vehiculo WHERE patente='POL715'), (SELECT id FROM chofer WHERE nombre='EDGARDO GOMEZ'), current_date),
((SELECT id FROM vehiculo WHERE patente='VTR198'), (SELECT id FROM chofer WHERE nombre='GABRIEL KALLEJOVSKY'), current_date),
((SELECT id FROM vehiculo WHERE patente='UEN183'), (SELECT id FROM chofer WHERE nombre='ARIEL ARANDA'), current_date),
((SELECT id FROM vehiculo WHERE patente='NGU658'), (SELECT id FROM chofer WHERE nombre='BRIAN LAZARTE'), current_date),
((SELECT id FROM vehiculo WHERE patente='AEP515'), (SELECT id FROM chofer WHERE nombre='LAJAR JOAQUIN'), current_date),
((SELECT id FROM vehiculo WHERE patente='GOY022'), (SELECT id FROM chofer WHERE nombre='MARIANO CANDIDA'), current_date),
((SELECT id FROM vehiculo WHERE patente='SCV537'), (SELECT id FROM chofer WHERE nombre='ESTEBAN ZELARAYAN'), current_date),
((SELECT id FROM vehiculo WHERE patente='BFP367'), (SELECT id FROM chofer WHERE nombre='VICTOR ACEVEDO'), current_date),
((SELECT id FROM vehiculo WHERE patente='AC750PI'), (SELECT id FROM chofer WHERE nombre='MAURO VERA'), current_date),
((SELECT id FROM vehiculo WHERE patente='JMR645'), (SELECT id FROM chofer WHERE nombre='HECTOR SUELDO'), current_date),
((SELECT id FROM vehiculo WHERE patente='AC134PT'), (SELECT id FROM chofer WHERE nombre='FEDERICO FLETES'), current_date),
((SELECT id FROM vehiculo WHERE patente='PNK597'), (SELECT id FROM chofer WHERE nombre='ESTEBAN GARCIA'), current_date),
((SELECT id FROM vehiculo WHERE patente='CIH935'), (SELECT id FROM chofer WHERE nombre='FRANCO GALVAN'), current_date),
((SELECT id FROM vehiculo WHERE patente='OMX055'), (SELECT id FROM chofer WHERE nombre='DIEGO ARRIOLA'), current_date),
((SELECT id FROM vehiculo WHERE patente='TUQ724'), (SELECT id FROM chofer WHERE nombre='JULIO CHAVEZ'), current_date),
((SELECT id FROM vehiculo WHERE patente='VWC443'), (SELECT id FROM chofer WHERE nombre='ALBERTO LAZOS'), current_date),
((SELECT id FROM vehiculo WHERE patente='JCA283'), (SELECT id FROM chofer WHERE nombre='HERNAN LABONIA'), current_date),
((SELECT id FROM vehiculo WHERE patente='GXW164'), (SELECT id FROM chofer WHERE nombre='GASTON RODRIGUEZ'), current_date),
((SELECT id FROM vehiculo WHERE patente='ACK453'), (SELECT id FROM chofer WHERE nombre='MATIAS PRACCA'), current_date),
((SELECT id FROM vehiculo WHERE patente='CCO178'), (SELECT id FROM chofer WHERE nombre='CRISTIAN GONZALEZ'), current_date),
((SELECT id FROM vehiculo WHERE patente='SYF050'), (SELECT id FROM chofer WHERE nombre='FELIX NIETO'), current_date);

-- parche
DELETE FROM chofer_vehiculo
WHERE id IN (
    SELECT id
    FROM (
        SELECT id,
               ROW_NUMBER() OVER (PARTITION BY id_chofer, id_vehiculo ORDER BY id) AS row_num
        FROM chofer_vehiculo
    ) AS subquery
    WHERE row_num > 1
);