INSERT INTO chofer (nombre, celular, dni, correo, fecha_creacion) VALUES
('NATALIA SANCHEZ', '1134732909', '11111111', NULL, current_date),
('NICOLAS NICHEA', '1155734426', '35370822', NULL, current_date),
('OMAR ARCE', '1161247243', '40043159', NULL, current_date),
('CESAR FELIPE PEREYRA', '1123906703', NULL, NULL, current_date),
('BRIAN CARDOZO', '1153263271', '34306645', NULL, current_date),
('COLTRINARI EDGARDO', '1130272407', '11488075', NULL, current_date),
('MORA WILFREDO', '1169968294', '26018251', NULL, current_date),
('MAXIMILIANO MARTORELLI', '1131930268', '33397180', NULL, current_date),
('GABRIEL DAMICO', '1163035127', '36298668', NULL, current_date),
('NICOLAS OVIEDO', '1126007747', '23694327', NULL, current_date),
('ADRIAN KUKIN', '1127264251', '20872603', NULL, current_date),
('DIEGO BARON', '1168266583', '28232554', NULL, current_date),
('GABRIEL DAMICO', '1132144070', '35391763', NULL, current_date),
('VICTOR  MAURO ZADIZ', '1148887259', '42284106', NULL, current_date),
('CORREA SERGIO', '1148887259', '25253284', NULL, current_date),
('ESTEBAN ZELARAYAN', NULL, '28984158', NULL, current_date),
('FABIAN ALEJANDRO ZELARAYAN', NULL, '23945420', NULL, current_date),
('JORGE ZELARAYAN', NULL, NULL, NULL, current_date),
('GASTON SUAREZ', '1169548366', '22275179', NULL, current_date),
('PABLO GERMAN DEL BARCO', '1161270172', '35168416', NULL, current_date),
('SEBASTIAN ORSOMARSO', '1167851169', '29330786', NULL, current_date),
('CRISTIAN VEGA', '1158917102', NULL, NULL, current_date),
('JOSE LUIS', '1165090308', NULL, NULL, current_date),
('ADRIAN CABRERA', '1167990800', NULL, NULL, current_date),
('HERNAN COROMINAS', '1137288040', NULL, NULL, current_date),
('ROMERO EDUARDO', '1136585707', '25897083', NULL, current_date),
('GUSTAVO GIUJUSA', '1153081529', '22508645', NULL, current_date),
('ANGELOZZI LEANDRO', NULL, '30236269', NULL, current_date),
('ENRIQUE ERCEGOVICH', NULL, '32822176', NULL, current_date),
('ZARAGOSA ROBERTO CARLOS', '1157598578', '36081880', NULL, current_date),
('DAMIAN ZANGARI', NULL, NULL, NULL, current_date),
('GASTON CABRERA', '1153786238', '36663290', NULL, current_date),
('HERNAN MONZON', NULL, NULL, NULL, current_date),
('JUAN BARRACCHIA', NULL, '28875894', NULL, current_date),
('IBER CALDERON', NULL, '111111111', NULL, current_date),
('EZEQUIEL ROBLEDO', NULL, NULL, NULL, current_date),
('MATIAS DIAZ', NULL, NULL, NULL, current_date),
('LUCAS ALANIZ', NULL, NULL, NULL, current_date),
('DAMIAN PLAZA', '1160230314', '24964339', NULL, current_date),
('FABIANA DYNOWSKY', '1165519152', '21460769', NULL, current_date),
('PORRO MARTIN', NULL, '69012280', NULL, current_date),
('MATIAS SILVEIRA', '1139281697', NULL, NULL, current_date),
('OSVALDO SILVEIRA', NULL, NULL, NULL, current_date),
('MATIAS NIEVAS', NULL, NULL, NULL, current_date),
('SUAREZ JULIO CESAR', NULL, NULL, NULL, current_date),
('NICOLAS LOTTA', NULL, NULL, NULL, current_date),
('JOSE MARQUEZ', NULL, NULL, NULL, current_date),
('LEANDRO SANDALIE', NULL, NULL, NULL, current_date),
('MARCELO DAMIAN FUNES', NULL, NULL, NULL, current_date),
('GOMEZ FEDERICO ANDRES', NULL, NULL, NULL, current_date),
('ACOSTA BRAIAN ARIEL', NULL, NULL, NULL, current_date),
('DANIEL ALBERTO ROBLEDO', NULL, NULL, NULL, current_date),
('SERGIO FUNES', NULL, NULL, NULL, current_date),
('DANIEL GUSTAVO GARCIA', NULL, NULL, NULL, current_date),
('SERGIO ARIEL AMARILLO', NULL, NULL, NULL, current_date),
('JESUS ELISEO CONDE', NULL, NULL, NULL, current_date),
('JUAN MANUEL LIND', NULL, NULL, NULL, current_date),
('SILVIA VELASCO', NULL, NULL, NULL, current_date),
('FERNANDO MARTINI', NULL, NULL, NULL, current_date),
('LEONARDO JAVIER ALVAREZ', NULL, NULL, NULL, current_date),
('ARIEL LUCERO', '1158831643', NULL, NULL, current_date),
('ISMAEL ESCOBAR', NULL, NULL, NULL, current_date),
('RICARDO PEREZ', NULL, NULL, NULL, current_date),
('GIAMMARINO ALEJANDRO', NULL, NULL, NULL, current_date),
('SERGIO VELA', '1139336880', NULL, NULL, current_date),
('CRISTIAN AGUIRRE', '1138759321', NULL, NULL, current_date),
('SERGIO MAIDANA', NULL, NULL, NULL, current_date),
('PABLO DANIEL DI BIASE', NULL, '24220535', NULL, current_date),
('GONZALO NAHUEL VESGA', NULL, NULL, NULL, current_date),
('IBER CALDERON', NULL, NULL, NULL, current_date),
('BRAGA RODOLFO MARTIN', NULL, NULL, NULL, current_date),
('JULIO CHAVEZ', NULL, NULL, NULL, current_date),
('SCOTTO LUCAS FABIAN', NULL, NULL, NULL, current_date),
('FEDERICO ALBORNOZ', NULL, NULL, NULL, current_date),
('ANDRADA ANGEL ALEJANDRO', NULL, NULL, NULL, current_date),
('JULIO LOBATO', NULL, NULL, NULL, current_date),
('DAMIAN MARTINEZ', NULL, NULL, NULL, current_date),
('MAXIMO FRANCISCO LEON', NULL, NULL, NULL, current_date),
('GUSTAVO RODRIGUEZ', NULL, NULL, NULL, current_date),
('MARCELO DI MAGGIO', NULL, NULL, NULL, current_date),
('ELIAS ALBERTO NUNEZ', NULL, NULL, NULL, current_date),
('SERGIO DENERI LOPEZ', NULL, NULL, NULL, current_date),
('SAVARRO ALEJANDRO', NULL, NULL, NULL, current_date),
('DIEGO CANOVAS', NULL, NULL, NULL, current_date),
('CRISTIAN AQUINO', NULL, NULL, NULL, current_date),
('ADRIAN GARRIGA', NULL, NULL, NULL, current_date),
('DAMIAN FLORES', NULL, NULL, NULL, current_date),
('RICARDO JAVIER TRIPODI', NULL, NULL, NULL, current_date),
('JOSE TORREL VICUNA', NULL, NULL, NULL, current_date),
('NESTOR AYALA', NULL, NULL, NULL, current_date),
('TOMAS SANFILIPO', NULL, NULL, NULL, current_date),
('EDGARDO ZELARAYAN', NULL, NULL, NULL, current_date),
('FEDERICO TREJO', NULL, NULL, NULL, current_date),
('CARLOS ARGARANAZ', NULL, NULL, NULL, current_date),
('LEONEL BORGES', NULL, NULL, NULL, current_date),
('CARLOS BERNANRDINO', NULL, NULL, NULL, current_date),
('JORGE MUR', NULL, NULL, NULL, current_date),
('GERONIMO FIGUEROA', NULL, NULL, NULL, current_date),
('LUCHA FABIAN', NULL, NULL, NULL, current_date),
('DANIELA DROGHETTI', NULL, NULL, NULL, current_date),
('GERARDO MARTÍN WOHN', NULL, NULL, NULL, current_date),
('GONZALO MASCOTENA', NULL, NULL, NULL, current_date),
('BRIAN AGUSTIN BERTOCHE', NULL, NULL, NULL, current_date),
('ALEX SOSA', NULL, NULL, NULL, current_date),
('CRISTIAN FERRER', NULL, NULL, NULL, current_date),
('MAURO PALACIOS', NULL, NULL, NULL, current_date),
('ANGEL RAFAEL', NULL, NULL, NULL, current_date),
('NARCISO LAUREANO GABRIEL', NULL, NULL, NULL, current_date),
('NICOLAS SIGNORELLI', NULL, NULL, NULL, current_date),
('GONZALO GERMAN FERNANDEZ', NULL, NULL, NULL, current_date),
('DIEGO SIMONE', NULL, NULL, NULL, current_date),
('JONATAN PINTO', NULL, NULL, NULL, current_date),
('FERREYRA FEDERICO FABIAN', NULL, NULL, NULL, current_date),
('SANTIAGO VIEDMA', NULL, NULL, NULL, current_date),
('GONZALO FARIS', NULL, NULL, NULL, current_date),
('LUCAS DARÍO GIANI', NULL, NULL, NULL, current_date),
('WINTER LEONARDO', NULL, NULL, NULL, current_date),
('LUIS VERA', NULL, NULL, NULL, current_date),
('PEDUTTI MIGUEL ANGEL', NULL, NULL, NULL, current_date),
('RODRIGO PEREZ', NULL, NULL, NULL, current_date),
('NAHUEL CARLOS GÓMEZ SEGOVIA', NULL, NULL, NULL, current_date),
('ACOSTA CARLOS DAVID', NULL, NULL, NULL, current_date),
('JULIAN ANDRES HERRERA', NULL, NULL, NULL, current_date),
('BRAYEN LAURA', NULL, NULL, NULL, current_date),
('HORACIO GABRIEL BARRERA', NULL, NULL, NULL, current_date),
('MUNOZ GONZALO', NULL, NULL, NULL, current_date),
('BUONAVENTURA BRIAN NAHUEL', NULL, NULL, NULL, current_date),
('DAMIAN GONZALES', NULL, NULL, NULL, current_date),
('FRÍAS HÉCTOR JOSÉ', NULL, NULL, NULL, current_date),
('RAMON ROMERO', NULL, NULL, NULL, current_date),
('SERRANO WALTER', NULL, NULL, NULL, current_date),
('JULIO ARRIONDO', NULL, NULL, NULL, current_date),
('OSCAR VILLALVA', NULL, NULL, NULL, current_date),
('MAXIMILIANO EDGARDO HILLAR', NULL, NULL, NULL, current_date),
('ERIBERTO JUARES PAVIA', NULL, NULL, NULL, current_date),
('FLORENTIN JORGE LUIS', NULL, NULL, NULL, current_date),
('GERMAN BORGES', NULL, NULL, NULL, current_date),
('DEPATRI MARTIN', NULL, NULL, NULL, current_date),
('CARMONA EMILIANO', NULL, NULL, NULL, current_date),
('CRISTIAN VALLEJOS', NULL, '35341498', NULL, current_date),
('PABLO LUCERO', NULL, NULL, NULL, current_date),
('RAMON GILS', NULL, NULL, NULL, current_date),
('LEIVA MARTIN', NULL, NULL, NULL, current_date),
('EMANUEL DOMINGUEZ', NULL, NULL, NULL, current_date),
('MAXIMILIANO GARCIA', NULL, NULL, NULL, current_date),
('FABIAN RODRIGUEZ', NULL, NULL, NULL, current_date),
('NICOLAS BOLLOTA', NULL, NULL, NULL, current_date),
('RUBEN SALCEDO', NULL, NULL, NULL, current_date),
('MAXIMILIANO LOBOS', NULL, NULL, NULL, current_date),
('JUAN AGUERO', NULL, NULL, NULL, current_date),
('JUAN FLORES', NULL, NULL, NULL, current_date),
('MAXIMILIANO RODRIGUEZ', NULL, NULL, NULL, current_date),
('JONATAN RODRIGUEZ', '1153263271', NULL, NULL, current_date),
('FERNANDO INTILANGELO', NULL, '27259951', NULL, current_date),
('ALEJANDRO FIGUEROA', NULL, NULL, NULL, current_date),
('JUAN GALINDRE', NULL, NULL, NULL, current_date),
('NICOLAS ZERDAN', NULL, NULL, NULL, current_date),
('JOEL CUELLA', NULL, NULL, NULL, current_date),
('MARTIN ABAN', '1135752328', NULL, NULL, current_date),
('ARIEL RUFAS', '1140418914', '30930043', NULL, current_date),
('FERNANDO INTILANGELO', NULL, NULL, NULL, current_date),
('ALEJANDRO DOMINGUEZ', NULL, NULL, NULL, current_date),
('DIEGO ROZZA', NULL, NULL, NULL, current_date),
('GONZALO MARINO', NULL, NULL, NULL, current_date),
('MARCELO OCAMPO', NULL, NULL, NULL, current_date),
('DAMIAN NICHEA', NULL, NULL, NULL, current_date),
('CRISTIAN MOLINA', NULL, NULL, NULL, current_date),
('GONZALO SANDOVAL', NULL, NULL, NULL, current_date),
('ANTONIO AZCONA', NULL, NULL, NULL, current_date),
('ELIO MOYA', NULL, NULL, NULL, current_date),
('NICOLAS CORREA', NULL, NULL, NULL, current_date),
('JONATAN PARDAL', NULL, NULL, NULL, current_date),
('MATIAS MIÃ±O', NULL, NULL, NULL, current_date),
('VESGA RUBEN', NULL, NULL, NULL, current_date),
('LEONARDO CARRIZO', NULL, NULL, NULL, current_date),
('VICTOR FERNANDEZ', NULL, NULL, NULL, current_date),
('CANO FACUNDO', NULL, NULL, NULL, current_date),
('DOMINGO TRIPPOLONI', NULL, NULL, NULL, current_date),
('MARCELO JUAN DAVID CASAS', NULL, NULL, NULL, current_date),
('JULIAN ARMENDARIZ', NULL, NULL, NULL, current_date),
('RODRIGO LAUTARO GRAMAJO', NULL, NULL, NULL, current_date),
('OMAR ARCE', NULL, NULL, NULL, current_date),
('NICOLAS NICHEA', NULL, NULL, NULL, current_date),
('DIEGO GASTON ESPINDOLA', NULL, NULL, NULL, current_date),
('SAMIR EMILIANO GALVAN', NULL, NULL, NULL, current_date),
('LEANDRO MACEDA', NULL, NULL, NULL, current_date),
('CLAUDIO RIVERA', NULL, NULL, NULL, current_date),
('NATALIA SANCHEZ', NULL, NULL, NULL, current_date),
('MAXIMILIANO MARTORELLI', NULL, NULL, NULL, current_date),
('GABRIEL DAMICO', NULL, NULL, NULL, current_date),
('DIEGO BARON', NULL, NULL, NULL, current_date),
('FABIAN ALEJANDRO ZELARAYAN', NULL, NULL, NULL, current_date),
('GASTON SUAREZ', NULL, NULL, NULL, current_date),
('PABLO GERMAN DEL BARCO', NULL, NULL, NULL, current_date),
('MARCELO GALINDRE', NULL, NULL, NULL, current_date),
('JOSE LUIS', NULL, NULL, NULL, current_date),
('ADRIAN CABRERA', NULL, NULL, NULL, current_date),
('HERNAN COROMINAS', NULL, NULL, NULL, current_date),
('MATIAS CASTILLO', NULL, NULL, NULL, current_date),
('ANGELOZZI LEANDRO', NULL, NULL, NULL, current_date),
('ZARAGOSA ROBERTO CARLOS', NULL, NULL, NULL, current_date),
('DAMIAN PLAZA', NULL, NULL, NULL, current_date),
('PORRO MARTIN', NULL, NULL, NULL, current_date),
('ARIEL LUCERO', NULL, NULL, NULL, current_date),
('CRISTIAN AGUIRRE', NULL, NULL, NULL, current_date),
('CRISTIAN VALLEJOS', NULL, NULL, NULL, current_date),
('MARTIN ABAN', NULL, NULL, NULL, current_date),
('ARIEL RUFAS', NULL, NULL, NULL, current_date),
('JUAN CARLOS SARAVIA', NULL, NULL, NULL, current_date),
('AQUINO RODRIGO', NULL, NULL, NULL, current_date),
('MIRANDA MARCELO SERGIO', NULL, NULL, NULL, current_date),
('JUAREZ DANIEL ADRIAN', NULL, NULL, NULL, current_date),
('ADRIAN MENDIETA', NULL, NULL, NULL, current_date),
('NELSON MARTÍNEZ', NULL, NULL, NULL, current_date),
('RICARDO CABALLERO', NULL, NULL, NULL, current_date),
('DARIO BUONAVENTURA', NULL, NULL, NULL, current_date),
('DANIEL DENIA', NULL, NULL, NULL, current_date),
('NICOLAS BORDALLO', NULL, NULL, NULL, current_date),
('SEBASTIAN EZEQUIEL BORDALLO', NULL, NULL, NULL, current_date),
('LEONEL DAVID', NULL, NULL, NULL, current_date),
('GABRIEL SUELDO', NULL, NULL, NULL, current_date),
('MATIAS AMORES', NULL, NULL, NULL, current_date),
('CRISTIAN MIÑO', NULL, NULL, NULL, current_date),
('NICOLAS MARTINO', NULL, NULL, NULL, current_date),
('JOSE FAZZINI', NULL, NULL, NULL, current_date),
('NICOLAS PEREZ', NULL, NULL, NULL, current_date),
('FRANCO ACUÑA', NULL, NULL, NULL, current_date),
('LEONARDO AMAYA', NULL, NULL, NULL, current_date),
('CRISTIAN MATEOS', NULL, NULL, NULL, current_date),
('LUIS SANCHEZ', NULL, NULL, NULL, current_date),
('WALTER PEÑATE', NULL, NULL, NULL, current_date),
('GUSTAVO CUBILLA', NULL, NULL, NULL, current_date),
('AMILCAR OPPEDISANO', NULL, NULL, NULL, current_date),
('EMANUEL BORDALLO', NULL, NULL, NULL, current_date),
('EZQUIEL ROBLEDO', NULL, NULL, NULL, current_date),
('LUIS REINOSO', NULL, NULL, NULL, current_date),
('EDGARDO GOMEZ', NULL, NULL, NULL, current_date),
('GABRIEL KALLEJOVSKY', NULL, NULL, NULL, current_date),
('ARIEL ARANDA', NULL, NULL, NULL, current_date),
('BRIAN LAZARTE', NULL, NULL, NULL, current_date),
('LAJAR JOAQUIN', NULL, NULL, NULL, current_date),
('MARIANO CANDIDA', NULL, NULL, NULL, current_date),
('ESTEBAN ZELARAYAN', NULL, NULL, NULL, current_date),
('VICTOR ACEVEDO', NULL, NULL, NULL, current_date),
('MAURO VERA', NULL, NULL, NULL, current_date),
('HECTOR SUELDO', NULL, NULL, NULL, current_date),
('FEDERICO FLETES', NULL, NULL, NULL, current_date),
('ESTEBAN GARCIA', NULL, NULL, NULL, current_date),
('FRANCO GALVAN', NULL, NULL, NULL, current_date),
('DIEGO ARRIOLA', NULL, NULL, NULL, current_date),
('ALBERTO LAZOS', NULL, NULL, NULL, current_date),
('HERNAN LABONIA', NULL, NULL, NULL, current_date),
('GASTON RODRIGUEZ', NULL, NULL, NULL, current_date),
('MATIAS PRACCA', NULL, NULL, NULL, current_date),
('CRISTIAN GONZALEZ', NULL, NULL, NULL, current_date),
('FELIX NIETO', NULL, NULL, NULL, current_date);

-- parches
UPDATE chofer SET nombre=UPPER(TRIM(nombre));
DELETE FROM chofer
WHERE (id) IN (
    SELECT id
    FROM (
        SELECT id, ROW_NUMBER() OVER (PARTITION BY nombre ORDER BY nombre) AS row_num
        FROM chofer
    ) subquery
    WHERE row_num > 1
);