INSERT INTO transporte (nombre, descripcion, fecha_creacion) VALUES
('DANIEL OSCAR DENIA', '', current_date),
('LUIS SANCHEZ', '', current_date),
('SEBASTIAN BORDALLO', '', current_date),
('ACOSTA CARLOS DAVID', '', current_date),
('ADRIAN MENDIETA', '', current_date),
('ALBERTO LAZOS', '', current_date),
('ALEX SOSA', '', current_date),
('AMILCAR OPPEDISANO', '', current_date),
('ANDRADA ANGEL ALEJANDRO', '', current_date),
('ANDREA LILIANA ALTAMIRANO', '', current_date),
('ANDRIAN MARCELO GARRIGA', '', current_date),
('ANGEL RAFAEL', '', current_date),
('ARIEL ARANDA', '', current_date),
('ARIEL LUCERO', '', current_date),
('BRAYEN LAURA', '', current_date),
('BRIAN', '', current_date),
('BRIAN AGUSTIN BERTOCHE', '', current_date),
('BUONAVENTURA BRIAN NAHUEL', '', current_date),
('CARLOS ALBERTO COROMINAS', '', current_date),
('CARLOS ARGARANAZ', '', current_date),
('CARLOS BERNANRDINO', '', current_date),
('CARLOS EZEQUIEL ROBLEDO', '', current_date),
('COLTRINARI EDGARDO', '', current_date),
('CRISTIAN AGUIRRE', '', current_date),
('CRISTIAN AQUINO', '', current_date),
('CRISTIAN MATEOS', '', current_date),
('CRISTIAN OMAR DORREGO', '', current_date),
('DAMIAN FLORES', '', current_date),
('DAMIAN GONZALES', '', current_date),
('DAMIAN MARTINEZ', '', current_date),
('DAMIAN OMAR PLAZA', '', current_date),
('DANIEL GARCIA', '', current_date),
('DANIELA DROGHETTI', '', current_date),
('DIEGO ARRIOLA', '', current_date),
('DIEGO CANOVAS', '', current_date),
('DIEGO DANIEL BARON', '', current_date),
('DIEGO GASTON ESPINDOLA', '', current_date),
('DIEGO SIMONE', '', current_date),
('EDGARDO GOMEZ', '', current_date),
('EDGARDO ZELARAYAN', '', current_date),
('EDUARDO SANTIAGO ROMERO', '', current_date),
('EL TURCO', '', current_date),
('ELIAS ALBERTO NUNEZ', '', current_date),
('ELIO ROMAN MOYA', '', current_date),
('EMANUEL BORDALLO', '', current_date),
('ENRIQUE ERCEGOVICH', '', current_date),
('ERIBERTO JUARES PAVIA', '', current_date),
('ESTEBAN GARCIA', '', current_date),
('FABIAN MATIAS EXEQUIEL SILVEIRA BONAFINA', '', current_date),
('FEDERICO FELTES', '', current_date),
('FEDERICO TREJO', '', current_date),
('FERREYRA FEDERICO FABIAN', '', current_date),
('FLORENCIO', '', current_date),
('FLORENTIN JORGE LUIS', '', current_date),
('FRANCO ACUÑA', '', current_date),
('FRANCO GALVAN', '', current_date),
('FRÍAS HÉCTOR JOSÉ', '', current_date),
('GABRIEL DAMICO', '', current_date),
('GABRIEL HORACIO LUDUENO', '', current_date),
('GABRIEL KALLEJOVSY', '', current_date),
('GASTON RODRIGUEZ', '', current_date),
('GERARDO MARTÍN WOHN', '', current_date),
('GERMAN BORGES', '', current_date),
('GERONIMO FIGUEROA', '', current_date),
('GONZALO FARIS', '', current_date),
('GONZALO GERMAN FERNANDEZ', '', current_date),
('GONZALO MASCOTENA', '', current_date),
('GRUPO MAF', '', current_date),
('GUSTAVO CUBILLA', '', current_date),
('HORACIO GABRIEL BARRERA', '', current_date),
('IBER CALDERON', '', current_date),
('JONATAN PARDAL GOMEZ', '', current_date),
('JONATAN PINTO', '', current_date),
('JORGE GUIMARAZ', '', current_date),
('JORGE MUR', '', current_date),
('JOSE ANTONIO PAREDES QUIZAMA', '', current_date),
('JOSE FAZZINI', '', current_date),
('JOSE TORREL VICUNA', '', current_date),
('JUAREZ DANIEL ADRIAN', '', current_date),
('JULIAN ANDRES HERRERA', '', current_date),
('JULIAN ARMENDARIS', '', current_date),
('JULIO ARRIONDO', '', current_date),
('JULIO LOBATO', '', current_date),
('LAJAR JOAQUIN', '', current_date),
('LEANDRO ALBERTO ANGELOZZI', '', current_date),
('LEONARDO AMAYA', '', current_date),
('LEONARDO GASTON SUAREZ', '', current_date),
('LOGISTICA SAN MARTIN', '', current_date),
('LUCAS DARÍO GIANI', '', current_date),
('LUCHA FABIAN', '', current_date),
('LUIS REINOSO', '', current_date),
('LUIS VERA', '', current_date),
('MARCELO DI MAGGIO', '', current_date),
('MARCELO JUAN DAVID CASAS', '', current_date),
('MARCELO OCAMPO', '', current_date),
('MARTIN ABAN', '', current_date),
('MATIAS CASTILLO', '', current_date),
('MATIAS NICOLAS DIAZ', '', current_date),
('MATIAS PRACCA', '', current_date),
('MAURO VERA', '', current_date),
('MAURO ZADIZ', '', current_date),
('MAXIMILIANO EDGARDO HILLAR', '', current_date),
('MAXIMILIANO MARTORELLI', '', current_date),
('MAXIMO FRANCISCO LEON', '', current_date),
('MIRANDA MARCELO SERGIO', '', current_date),
('MUNOZ GONZALO', '', current_date),
('NAHUEL CARLOS GÓMEZ SEGOVIA', '', current_date),
('NARCISO LAUREANO GABRIEL', '', current_date),
('NESTOR', '', current_date),
('NESTOR AYALA', '', current_date),
('NICHEA DAMIAN ALEXIS', '', current_date),
('NICOLAS NICHEA', '', current_date),
('NICOLAS OVIEDO', '', current_date),
('NICOLAS SIGNORELLI', '', current_date),
('OMAR ARCE', '', current_date),
('OSCAR VILLALVA', '', current_date),
('OSVALDO BORDALLO', '', current_date),
('PABLO  LUCERO', '', current_date),
('PEDUTTI MIGUEL ANGEL', '', current_date),
('PEREYRA', '', current_date),
('RAMON ROMERO', '', current_date),
('RICARDO JAVIER TRIPODI', '', current_date),
('RODRIGO PEREZ', '', current_date),
('SAMIR EMILIANO GALVAN', '', current_date),
('SANTIAGO VIEDMA', '', current_date),
('SAVARRO ALEJANDRO', '', current_date),
('SEBASTIAN BORDALLO', '', current_date),
('SERGIO DENERI LOPEZ', '', current_date),
('SERGIO HERNAN MAIDANA', '', current_date),
('SERGIO VELA', '', current_date),
('SERRANO WALTER', '', current_date),
('SILVIA NOEMI VELASCO', '', current_date),
('SILVIA VELASCO', '', current_date),
('SILVIO GIAMBUZZI', '', current_date),
('SOLEDAD VICTORIA CHEMTOB', '', current_date),
('SUSANA FABIANA DYNOWSKY', '', current_date),
('TOMAS SANFILIPO', '', current_date),
('TRANSOESTE', '', current_date),
('TRANSOESTE SRL', '', current_date),
('VASTRANS', '', current_date),
('WALTER PEÑATE', '', current_date),
('WINTER LEONARDO', '', current_date),
('ZARAGOZA ROBERTO CARLOS', '', current_date);

-- parche
DELETE FROM transporte
WHERE id NOT IN (
    SELECT MIN(id)
    FROM transporte
    GROUP BY nombre
);

UPDATE transporte SET nombre=TRIM(nombre);